### ISSUE TITLE
Shared workbook

### ISSUE THREAD

**Issue by avalanche1** [awsp/handsontable-meteor#25]
Hi! Thanks for all your work!
I'd like to know if there's a way to have a 'shared' workbook functionality in Meteor - when several users work on the same workbook?
I'd like to be able to lock out cells if they are selected by another user and to have notifications when a user edited smth on the shared workbook. - Is that possible with your package (theoretically)?

**Comment by awsp** [comment]
Yes, I was using this package in a meteor project mainly for the purpose on allowing multiple users to be able to edit the same workbook couple months ago. Although it is not finished, technically you would need to watch the pub/sub and update the workbook accordingly. I even allow people to see each other which cell they are currently selecting with colors. 

But one thing is you could have to update the cell directly instead of doing loadData when something changed since you don't want to erase others who's trying to type.

So technically locking out the cell is possible. In my case, take a look at meteor pub/sub system (instead of using the official you override you own to keep track of who's subscribed, and did what), as well as the use of client-only mongo. 

Hope it helps.

**Comment by avalanche1** [comment]
Could you expand on  

> the use of client-only mongo

 for this particular case?

**Comment by awsp** [comment]
Sorry for the late reply, I  thought I submitted the comment, but it was left and saved into my virtual machine ...lol

Okay, so in my case, I used Meteor's pub to publish to client-only mongo with recording their subscription ID so I could manage all the subscriptions, the use of client-only mongo is because I would like to avoid having people directly overwriting each others' data via DDP. Client-only database allows 1 way transfer so any data get saved will need to pass thru a gateway that I could better take control to. (Might not be the best way, but it suits my needs during that time).

Hope it helps.

**Comment by avalanche1** [comment]
Hmmm... I was thinking of simply locking out selected cells (by marking that cell in db as locked), so only the person who selected the cell first could write to it. What do you think of that approach?

**Comment by awsp** [comment]
Yea, I agree in some extend locking the cell would definitely do. I was just trying to do the same thing Google Sheet does. :D Best of luck.

**Comment by awsp** [comment]
Closing this issue.
