### ISSUE TITLE
in "Important Notes"

### ISSUE THREAD

**Issue by jm4r7in** [awsp/handsontable-meteor#9]
Replace 
`var container = hot, document.getElementById('hot');`
by
`var container = document.getElementById('hot');`

And thanks a lot for the package!

**Comment by awsp** [comment]
Thanks for your comment. 

Yea, you are right, didn't notice there was an error in the example, was copying from Handsontable docs straight. But I think you would still need `hot` variable to store the reference to Handsontable, so I will change the code a little bit. 

See commit: 7a75085

Since this is a quick fix, I am not going to push to atmosphere as versioning remains to be 0.8.0. 
Changes will be reflected on Atmosphere next time when there is a version change. 
Thanks!
